<template>
  <div class="requirements">
    <div class="page-header">
      <h1>格式要求管理</h1>
      <button @click="openAddDialog" class="btn btn-primary">+ 添加要求</button>
    </div>

    <!-- 空状态 -->
    <div v-if="requirementList.length === 0 && !loading" class="empty-state">
      <p>暂无格式要求，请点击"添加要求"上传规范文件</p>
    </div>

    <!-- 加载中 -->
    <div v-if="loading" class="loading-text">加载中...</div>

    <!-- 列表 -->
    <div class="requirement-list">
      <div v-for="item in requirementList" :key="item.id" class="requirement-item">
        <div class="item-header">
          <div class="item-meta">
            <h3>{{ item.name }}</h3>
            <span class="tag" :class="item.type === 'school' ? 'tag-blue' : 'tag-green'">
              {{ item.type === 'school' ? '校级规范' : '专业规范' }}
            </span>
            <span v-if="item.major" class="tag tag-gray">{{ item.major }}</span>
          </div>
          <div class="item-actions">
            <button @click="removeRequirement(item.id)" class="btn btn-small btn-danger">删除</button>
          </div>
        </div>
        <div class="item-content">
          <p class="content-preview">{{ item.content ? item.content.slice(0, 200) + (item.content.length > 200 ? '...' : '') : '（无内容预览）' }}</p>
          <p class="item-time">上传时间：{{ formatDate(item.created_at) }}</p>
        </div>
      </div>
    </div>

    <!-- 添加要求弹窗 -->
    <div v-if="showDialog" class="modal-overlay" @click.self="closeDialog">
      <div class="modal-box">
        <div class="modal-header">
          <h3>添加格式要求</h3>
          <button class="close-btn" @click="closeDialog">✕</button>
        </div>

        <div class="form-group">
          <label>要求名称 <span class="required">*</span></label>
          <input v-model="form.name" type="text" class="form-input" placeholder="例如：2024届毕业论文格式规范" @input="nameAutoGenerated = false" />
        </div>

        <div class="form-group">
          <label>类型 <span class="required">*</span></label>
          <select v-model="form.type" class="form-input">
            <option value="school">校级规范</option>
            <option value="major">专业规范</option>
          </select>
        </div>

        <div class="form-group" v-if="form.type === 'major'">
          <label>专业名称</label>
          <input v-model="form.major" type="text" class="form-input" placeholder="例如：软件工程" />
        </div>

        <div class="form-group">
          <label>规范文件 <span class="required">*</span></label>
          <div class="file-upload-area" @click="triggerFileInput" @dragover.prevent @drop.prevent="handleDrop">
            <input ref="fileInput" type="file" accept=".md,.txt,.docx,.doc,.pdf" style="display:none" @change="handleFileChange" />
            <div v-if="!form.file" class="upload-placeholder">
              <span class="upload-icon">📄</span>
              <p>点击选择文件或拖拽到此处</p>
              <p class="file-hint">支持 .md / .txt / .docx / .doc / .pdf 格式</p>
            </div>
            <div v-else class="file-selected">
              <span>📎 {{ form.file.name }}</span>
              <button class="remove-file" @click.stop="form.file = null">✕</button>
            </div>
          </div>
        </div>

        <p v-if="errorMsg" class="error-msg">{{ errorMsg }}</p>

        <div class="modal-footer">
          <button class="btn btn-cancel" @click="closeDialog">取消</button>
          <button class="btn btn-primary" :disabled="submitting" @click="submitAdd">
            {{ submitting ? '上传中...' : '确认添加' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, reactive, watch } from 'vue'
import { getRequirements, uploadRequirement, deleteRequirement } from '@/api/admin'

const requirementList = ref([])
const loading = ref(false)
const showDialog = ref(false)
const submitting = ref(false)
const errorMsg = ref('')
const fileInput = ref(null)
// NOTE: 用于判断名称是否由系统自动生成，若是则在文件/类型改变时可自动更新
const nameAutoGenerated = ref(false)

const form = reactive({
  name: '',
  type: 'school',
  major: '',
  file: null
})

/**
 * 根据当前文件名、类型和日期生成默认要求名称
 * @param {File|null} file 选中的文件
 * @param {string} type 规范类型
 * @returns {string}
 */
const generateDefaultName = (file, type) => {
  const typeLabel = type === 'school' ? '校级规范' : '专业规范'
  const now = new Date()
  const dateStr = `${now.getFullYear()}年${now.getMonth() + 1}月${now.getDate()}日`
  if (file) {
    const baseName = file.name.replace(/\.[^.]+$/, '') // 去掉扩展名
    return `${baseName}（${typeLabel}）`
  }
  return `${typeLabel}-${dateStr}`
}

// 监听类型变化：若名称是自动生成的，随类型更新名称
watch(() => form.type, (newType) => {
  if (nameAutoGenerated.value) {
    form.name = generateDefaultName(form.file, newType)
  }
})

onMounted(() => {
  fetchRequirements()
})

const fetchRequirements = async () => {
  loading.value = true
  try {
    const res = await getRequirements()
    requirementList.value = Array.isArray(res) ? res : []
  } catch (error) {
    console.error('获取格式要求失败:', error)
  } finally {
    loading.value = false
  }
}

const openAddDialog = () => {
  form.name = generateDefaultName(null, form.type)
  form.type = 'school'
  form.major = ''
  form.file = null
  nameAutoGenerated.value = true
  errorMsg.value = ''
  showDialog.value = true
}

const closeDialog = () => {
  showDialog.value = false
}

const triggerFileInput = () => {
  fileInput.value?.click()
}

const handleFileChange = (e) => {
  const file = e.target.files[0]
  if (file) {
    form.file = file
    // 选文件后，用文件名自动更新字段（若名称仍是自动生成的）
    if (nameAutoGenerated.value) {
      form.name = generateDefaultName(file, form.type)
    }
  }
}

const handleDrop = (e) => {
  const file = e.dataTransfer.files[0]
  if (file) {
    form.file = file
    if (nameAutoGenerated.value) {
      form.name = generateDefaultName(file, form.type)
    }
  }
}

const submitAdd = async () => {
  errorMsg.value = ''
  if (!form.name.trim()) {
    errorMsg.value = '请填写要求名称'
    return
  }
  if (!form.file) {
    errorMsg.value = '请选择规范文件'
    return
  }
  if (form.type === 'major' && !form.major.trim()) {
    errorMsg.value = '专业规范请填写专业名称'
    return
  }

  submitting.value = true
  try {
    await uploadRequirement({
      name: form.name,
      type: form.type,
      major: form.type === 'major' ? form.major : undefined,
      file: form.file
    })
    closeDialog()
    fetchRequirements()
  } catch (error) {
    errorMsg.value = '上传失败，请检查文件格式是否正确'
    console.error(error)
  } finally {
    submitting.value = false
  }
}

const removeRequirement = async (id) => {
  if (!confirm('确定要删除这条格式要求吗？')) return
  try {
    await deleteRequirement(id)
    fetchRequirements()
  } catch (error) {
    console.error('删除失败:', error)
    alert('删除失败，请重试')
  }
}

/**
 * 格式化日期字符串为本地时间
 * @param {string} dateStr ISO 时间字符串
 * @returns {string} 本地格式化日期
 */
const formatDate = (dateStr) => {
  if (!dateStr) return '-'
  return new Date(dateStr).toLocaleString('zh-CN')
}
</script>

<style scoped>
.requirements {
  padding: 24px;
}

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 24px;
}

.page-header h1 {
  font-size: 22px;
  color: #1a1a2e;
  margin: 0;
}

.empty-state {
  text-align: center;
  padding: 60px 0;
  color: #999;
}

.loading-text {
  text-align: center;
  padding: 40px;
  color: #999;
}

.requirement-list {
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.requirement-item {
  padding: 20px;
  background: #fff;
  border-radius: 10px;
  box-shadow: 0 2px 10px rgba(0,0,0,0.07);
  border-left: 4px solid #667eea;
}

.item-meta {
  display: flex;
  align-items: center;
  gap: 10px;
}

.item-meta h3 {
  margin: 0;
  font-size: 16px;
  color: #303133;
}

.tag {
  font-size: 11px;
  padding: 2px 8px;
  border-radius: 10px;
  font-weight: 500;
}
.tag-blue { background: #e8f0fe; color: #3367d6; }
.tag-green { background: #e6f4ea; color: #1e8e3e; }
.tag-gray { background: #f1f3f4; color: #5f6368; }

.item-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 12px;
}

.item-actions {
  display: flex;
  gap: 8px;
}

.content-preview {
  font-size: 13px;
  color: #666;
  line-height: 1.6;
  white-space: pre-wrap;
  margin: 0 0 8px;
}

.item-time {
  font-size: 12px;
  color: #aaa;
  margin: 0;
}

/* 按钮 */
.btn {
  padding: 8px 18px;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  font-size: 14px;
  transition: opacity 0.2s;
}
.btn:hover { opacity: 0.85; }
.btn:disabled { opacity: 0.5; cursor: not-allowed; }

.btn-primary {
  background: #667eea;
  color: #fff;
}
.btn-small {
  padding: 4px 10px;
  font-size: 12px;
}
.btn-danger {
  background: #ff4d4f;
  color: #fff;
}
.btn-cancel {
  background: #f0f0f0;
  color: #555;
}

/* 弹窗 */
.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.45);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 9999;
}

.modal-box {
  background: #fff;
  border-radius: 12px;
  padding: 28px;
  width: 480px;
  max-width: 95vw;
  box-shadow: 0 20px 60px rgba(0,0,0,0.2);
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 24px;
}

.modal-header h3 {
  margin: 0;
  font-size: 18px;
  color: #1a1a2e;
}

.close-btn {
  background: none;
  border: none;
  font-size: 18px;
  cursor: pointer;
  color: #999;
  padding: 0 4px;
}
.close-btn:hover { color: #333; }

.form-group {
  margin-bottom: 18px;
}

.form-group label {
  display: block;
  margin-bottom: 6px;
  font-size: 14px;
  color: #555;
}

.required {
  color: #ff4d4f;
}

.form-input {
  width: 100%;
  height: 38px;
  padding: 0 12px;
  border: 1px solid #dcdfe6;
  border-radius: 6px;
  font-size: 14px;
  color: #303133;
  box-sizing: border-box;
  outline: none;
  transition: border-color 0.2s;
}
.form-input:focus { border-color: #667eea; }

/* 文件上传区域 */
.file-upload-area {
  border: 2px dashed #d0d0d0;
  border-radius: 8px;
  padding: 24px;
  text-align: center;
  cursor: pointer;
  transition: border-color 0.2s, background 0.2s;
}
.file-upload-area:hover { border-color: #667eea; background: #f8f8ff; }

.upload-placeholder {
  color: #999;
}
.upload-icon { font-size: 32px; }
.upload-placeholder p { margin: 6px 0; font-size: 14px; }
.file-hint { font-size: 12px; color: #bbb; }

.file-selected {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 12px;
  font-size: 14px;
  color: #333;
}
.remove-file {
  background: none;
  border: none;
  cursor: pointer;
  color: #999;
  font-size: 16px;
}
.remove-file:hover { color: #f00; }

.error-msg {
  color: #ff4d4f;
  font-size: 13px;
  margin: 0 0 12px;
}

.modal-footer {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
  margin-top: 20px;
}
</style>
