<template>
  <div class="templates-page">
    <div class="page-header">
      <h1>📄 书写模板管理</h1>
      <button @click="openAddDialog" class="btn btn-primary">+ 上传模板</button>
    </div>

    <!-- 分类 Tab -->
    <div class="tabs">
      <button
        v-for="tab in tabs"
        :key="tab.key"
        :class="['tab-btn', { active: activeTab === tab.key }]"
        @click="activeTab = tab.key"
      >
        {{ tab.label }}<span class="count">{{ countByCategory(tab.key) }}</span>
      </button>
    </div>

    <!-- 加载 -->
    <div v-if="loading" class="loading-text">加载中...</div>

    <!-- 空状态 -->
    <div v-if="!loading && filteredList.length === 0" class="empty-state">
      <p>暂无{{ tabs.find(t=>t.key===activeTab)?.label }}模板</p>
    </div>

    <!-- 列表 -->
    <div class="template-grid">
      <div v-for="item in filteredList" :key="item.id" class="template-card">
        <div class="card-icon">{{ fileIcon(item.file_type) }}</div>
        <div class="card-body">
          <h3 class="card-title">{{ item.name }}</h3>
          <p v-if="item.description" class="card-desc">{{ item.description }}</p>
          <div class="card-meta">
            <span class="tag" :class="categoryTag(item.category)">
              {{ categoryLabel(item.category) }}
            </span>
            <span class="file-type">.{{ item.file_type }}</span>
          </div>
          <p class="card-time">上传：{{ formatDate(item.created_at) }}</p>
        </div>
        <div class="card-actions">
          <a :href="`/api/templates/${item.id}/download`" target="_blank" class="btn btn-download">
            ⬇ 下载
          </a>
          <button @click="removeTemplate(item.id)" class="btn btn-small btn-danger">删除</button>
        </div>
      </div>
    </div>

    <!-- 上传弹窗 -->
    <div v-if="showDialog" class="modal-overlay" @click.self="closeDialog">
      <div class="modal-box">
        <div class="modal-header">
          <h3>上传书写模板</h3>
          <button class="close-btn" @click="closeDialog">✕</button>
        </div>

        <div class="form-group">
          <label>模板名称 <span class="required">*</span></label>
          <input
            v-model="form.name"
            type="text"
            class="form-input"
            placeholder="例如：2024届毕业论文完整模板"
            @input="nameAutoGenerated = false"
          />
        </div>

        <div class="form-group">
          <label>模板类型 <span class="required">*</span></label>
          <select v-model="form.category" class="form-input" @change="onCategoryChange">
            <option value="full">完整模板（含封面/正文/参考文献）</option>
            <option value="cover">封面页模板</option>
            <option value="body">正文模板</option>
            <option value="reference">参考文献模板</option>
          </select>
        </div>

        <div class="form-group">
          <label>模板描述</label>
          <textarea
            v-model="form.description"
            class="form-input form-textarea"
            placeholder="简要描述适用范围、版本等信息（选填）"
            rows="3"
          ></textarea>
        </div>

        <div class="form-group">
          <label>模板文件 <span class="required">*</span></label>
          <div
            class="file-upload-area"
            @click="triggerFileInput"
            @dragover.prevent
            @drop.prevent="handleDrop"
          >
            <input
              ref="fileInput"
              type="file"
              accept=".docx,.doc,.pdf,.md,.txt"
              style="display:none"
              @change="handleFileChange"
            />
            <div v-if="!form.file" class="upload-placeholder">
              <span class="upload-icon">📥</span>
              <p>点击选择文件或拖拽到此处</p>
              <p class="file-hint">支持 .docx / .doc / .pdf / .md / .txt</p>
            </div>
            <div v-else class="file-selected">
              <span>📎 {{ form.file.name }}</span>
              <button class="remove-file" @click.stop="form.file = null">✕</button>
            </div>
          </div>
        </div>

        <p v-if="errorMsg" class="error-msg">{{ errorMsg }}</p>

        <div class="modal-footer">
          <button class="btn btn-cancel" @click="closeDialog">取消</button>
          <button class="btn btn-primary" :disabled="submitting" @click="submitUpload">
            {{ submitting ? '上传中...' : '确认上传' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, computed, onMounted, watch } from 'vue'
import { getTemplates, uploadTemplate, deleteTemplate } from '@/api/admin'

const templateList = ref([])
const loading = ref(false)
const showDialog = ref(false)
const submitting = ref(false)
const errorMsg = ref('')
const fileInput = ref(null)
const nameAutoGenerated = ref(false)
const activeTab = ref('all')

const tabs = [
  { key: 'all',       label: '全部' },
  { key: 'full',      label: '完整模板' },
  { key: 'cover',     label: '封面模板' },
  { key: 'body',      label: '正文模板' },
  { key: 'reference', label: '参考文献' },
]

const form = reactive({
  name: '',
  category: 'full',
  description: '',
  file: null
})

const filteredList = computed(() => {
  if (activeTab.value === 'all') return templateList.value
  return templateList.value.filter(t => t.category === activeTab.value)
})

const countByCategory = (key) => {
  if (key === 'all') return templateList.value.length
  return templateList.value.filter(t => t.category === key).length
}

onMounted(fetchTemplates)

async function fetchTemplates() {
  loading.value = true
  try {
    const res = await getTemplates()
    templateList.value = Array.isArray(res) ? res : []
  } catch (e) {
    console.error('获取模板失败', e)
  } finally {
    loading.value = false
  }
}

/**
 * 根据文件名和类型自动生成默认模板名称
 * @param {File|null} file
 * @param {string} category
 */
const generateName = (file, category) => {
  const label = categoryLabel(category)
  const now = new Date()
  const date = `${now.getFullYear()}年${now.getMonth()+1}月`
  if (file) {
    const base = file.name.replace(/\.[^.]+$/, '')
    return `${base}（${label}）`
  }
  return `${label}-${date}`
}

const openAddDialog = () => {
  form.name = generateName(null, form.category)
  form.category = 'full'
  form.description = ''
  form.file = null
  nameAutoGenerated.value = true
  errorMsg.value = ''
  showDialog.value = true
}

const onCategoryChange = () => {
  if (nameAutoGenerated.value) {
    form.name = generateName(form.file, form.category)
  }
}

watch(() => form.category, () => {
  if (nameAutoGenerated.value) form.name = generateName(form.file, form.category)
})

const closeDialog = () => { showDialog.value = false }

const triggerFileInput = () => fileInput.value?.click()

const handleFileChange = (e) => {
  const file = e.target.files[0]
  if (file) {
    form.file = file
    if (nameAutoGenerated.value) form.name = generateName(file, form.category)
  }
}

const handleDrop = (e) => {
  const file = e.dataTransfer.files[0]
  if (file) {
    form.file = file
    if (nameAutoGenerated.value) form.name = generateName(file, form.category)
  }
}

const submitUpload = async () => {
  errorMsg.value = ''
  if (!form.name.trim()) { errorMsg.value = '请填写模板名称'; return }
  if (!form.file) { errorMsg.value = '请选择模板文件'; return }

  submitting.value = true
  try {
    await uploadTemplate({
      name: form.name,
      category: form.category,
      description: form.description || undefined,
      file: form.file
    })
    closeDialog()
    fetchTemplates()
  } catch (e) {
    errorMsg.value = '上传失败，请检查文件格式是否正确'
    console.error(e)
  } finally {
    submitting.value = false
  }
}

const removeTemplate = async (id) => {
  if (!confirm('确定要删除此模板吗？')) return
  try {
    await deleteTemplate(id)
    fetchTemplates()
  } catch (e) {
    alert('删除失败，请重试')
    console.error(e)
  }
}

// ── 辅助函数 ──────────────────────────
const categoryLabel = (cat) => {
  const map = { full: '完整模板', cover: '封面模板', body: '正文模板', reference: '参考文献' }
  return map[cat] || cat
}
const categoryTag = (cat) => {
  const map = { full: 'tag-purple', cover: 'tag-blue', body: 'tag-green', reference: 'tag-orange' }
  return map[cat] || ''
}
const fileIcon = (ext) => {
  const map = { docx: '📝', pdf: '📕', md: '📋', txt: '📄' }
  return map[ext] || '📄'
}

/**
 * 格式化日期
 * @param {string} d ISO 时间字符串
 */
const formatDate = (d) => d ? new Date(d).toLocaleString('zh-CN') : '-'
</script>

<style scoped>
.templates-page { padding: 24px; }

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}
.page-header h1 { margin: 0; font-size: 22px; }

/* Tabs */
.tabs { display: flex; gap: 8px; margin-bottom: 20px; flex-wrap: wrap; }
.tab-btn {
  padding: 7px 16px;
  border: 1px solid #d9d9d9;
  border-radius: 20px;
  background: #fff;
  cursor: pointer;
  font-size: 13px;
  color: #555;
  transition: all 0.2s;
}
.tab-btn.active { background: #667eea; border-color: #667eea; color: #fff; }
.count {
  display: inline-block;
  margin-left: 5px;
  background: rgba(0,0,0,0.12);
  border-radius: 10px;
  padding: 0 6px;
  font-size: 11px;
}

/* Grid */
.template-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 16px;
}

.template-card {
  background: #fff;
  border-radius: 12px;
  box-shadow: 0 2px 12px rgba(0,0,0,0.08);
  padding: 20px;
  display: flex;
  flex-direction: column;
  gap: 12px;
  border-top: 4px solid #667eea;
  transition: transform 0.2s, box-shadow 0.2s;
}
.template-card:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0,0,0,0.12); }

.card-icon { font-size: 36px; }
.card-body { flex: 1; }
.card-title { margin: 0 0 6px; font-size: 15px; color: #1a1a2e; }
.card-desc { margin: 0 0 8px; font-size: 13px; color: #888; line-height: 1.5; }
.card-meta { display: flex; align-items: center; gap: 8px; margin-bottom: 6px; }
.file-type { font-size: 12px; color: #aaa; background: #f5f5f5; padding: 2px 6px; border-radius: 4px; }
.card-time { margin: 0; font-size: 12px; color: #bbb; }

.tag { font-size: 11px; padding: 2px 8px; border-radius: 10px; font-weight: 500; }
.tag-purple  { background: #f3f0ff; color: #7c3aed; }
.tag-blue    { background: #e8f0fe; color: #3367d6; }
.tag-green   { background: #e6f4ea; color: #1e8e3e; }
.tag-orange  { background: #fff3e0; color: #e65100; }

.card-actions { display: flex; gap: 8px; }

/* 按钮 */
.btn { padding: 8px 18px; border: none; border-radius: 6px; cursor: pointer; font-size: 13px; transition: opacity 0.2s; }
.btn:hover { opacity: 0.85; }
.btn:disabled { opacity: 0.5; cursor: not-allowed; }
.btn-primary { background: #667eea; color: #fff; }
.btn-download { background: #10b981; color: #fff; text-decoration: none; display: inline-flex; align-items: center; }
.btn-small { padding: 4px 10px; font-size: 12px; }
.btn-danger { background: #ff4d4f; color: #fff; }
.btn-cancel { background: #f0f0f0; color: #555; }

.loading-text, .empty-state { text-align: center; padding: 60px; color: #999; }

/* 弹窗 */
.modal-overlay {
  position: fixed; inset: 0;
  background: rgba(0,0,0,0.45);
  display: flex; align-items: center; justify-content: center;
  z-index: 9999;
}
.modal-box {
  background: #fff;
  border-radius: 12px;
  padding: 28px;
  width: 500px; max-width: 95vw;
  box-shadow: 0 20px 60px rgba(0,0,0,0.2);
}
.modal-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 22px; }
.modal-header h3 { margin: 0; font-size: 18px; }
.close-btn { background: none; border: none; font-size: 18px; cursor: pointer; color: #999; }
.close-btn:hover { color: #333; }

.form-group { margin-bottom: 16px; }
.form-group label { display: block; margin-bottom: 6px; font-size: 14px; color: #555; }
.required { color: #ff4d4f; }
.form-input {
  width: 100%; padding: 8px 12px;
  border: 1px solid #dcdfe6; border-radius: 6px;
  font-size: 14px; color: #303133;
  box-sizing: border-box; outline: none;
  transition: border-color 0.2s;
}
.form-input:focus { border-color: #667eea; }
.form-textarea { height: auto; resize: vertical; }

.file-upload-area {
  border: 2px dashed #d0d0d0; border-radius: 8px;
  padding: 24px; text-align: center; cursor: pointer;
  transition: border-color 0.2s, background 0.2s;
}
.file-upload-area:hover { border-color: #667eea; background: #f8f8ff; }
.upload-placeholder { color: #999; }
.upload-icon { font-size: 30px; }
.upload-placeholder p { margin: 6px 0; font-size: 14px; }
.file-hint { font-size: 12px; color: #bbb; }
.file-selected { display: flex; align-items: center; justify-content: center; gap: 12px; font-size: 14px; color: #333; }
.remove-file { background: none; border: none; cursor: pointer; color: #999; font-size: 16px; }
.remove-file:hover { color: #f00; }

.error-msg { color: #ff4d4f; font-size: 13px; margin: 0 0 12px; }
.modal-footer { display: flex; justify-content: flex-end; gap: 10px; margin-top: 20px; }
</style>
